default_stages: [pre-commit, pre-push]

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-yaml
        args:
          - --allow-multiple-documents
          - --unsafe
      - id: end-of-file-fixer
      - id: mixed-line-ending
        args:
          - --fix=auto
      - id: trailing-whitespace
      - id: check-merge-conflict
      - id: destroyed-symlinks
      - id: check-symlinks
  - repo: https://github.com/tcort/markdown-link-check
    rev: v3.11.2
    hooks:
      - id: markdown-link-check
        args: [-q]
